# Usando a imagem do Node.js
FROM node:18

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o package.json e package-lock.json
COPY package.json package-lock.json ./
RUN npm install

# Copiar o código do projeto
COPY . .

# Passa a variável API_KEY
ARG GOOGLE_API_KEY
ENV REACT_APP_GOOGLE_API_KEY=$GOOGLE_API_KEY

# Expor a porta 80
EXPOSE 80

# Rodar o servidor de desenvolvimento do React
CMD ["npm", "start"]