# Usando uma imagem do Node.js
FROM node:18

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o package.json e package-lock.json
COPY package.json package-lock.json ./
RUN npm install

# Copiar todo o código do projeto
COPY . .

# Passa a variável API_KEY
ARG GOOGLE_API_KEY
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY

# Instalar as dependências de desenvolvimento, como o `nodemon`
RUN npm install --only=development

# Expor a porta 8080
EXPOSE 8080

# Rodar o servidor com nodemon
CMD ["npm", "run", "dev"]