# Dockerfile para o backend
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos necessários
COPY package*.json ./
COPY tsconfig.json ./

# Instala as dependências
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta da API
EXPOSE 8080

# Comando para iniciar o servidor
CMD ["npm", "run", "start"]
